FROM ollama/ollama:latest

WORKDIR /home/reis/IAC/Ollama_openclaw_build

RUN apt update && apt install curl  -y  

RUN curl -fsSL https://openclaw.ai/install.sh | bash -s -- --no-onboard












Web UI: http://127.0.0.1:18789/                                                 │
│  Web UI (with token):                                                            │
│  http://127.0.0.1:18789/#token=3214ff135ff5996992717912b081b6bffeb587d5d01b86d3  │
│  Gateway WS: ws://127.0.0.1:18789                                                │
│  Gateway: not detected (connect ECONNREFUSED 127.0.0.1:18789)                    │
│  Docs: https://docs.openclaw.ai/web/control-ui   