

services:
  
  n8n:
    
    image: n8nio/n8n
    
    container_name: automation
    
    hostname: n8n
    
    ports:
      - "5678:5678"

    volumes:
      - data_n8n:/home/node/.n8n
    
    restart: always

volumes:
  data_n8n:


